apiVersion: v1
kind: Service
metadata:
  labels:
    app: pr-checker-workflow
  name: pr-checker-workflow-http
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: pr-checker-workflow
  sessionAffinity: None
  type: ClusterIP

